export const queryParams = {
  minPax: 'min_pax',
  opsFrom: 'ops_from',
  isWide: 'is_wide',
  dates: 'date_from,date_to',
  iosa: 'iosa',
  act: 'act',
  galley: 'galley',
  wifi: 'wifi',
  ife: 'ife',
  isps: 'isps',
  allMaleCrew: 'all_male_crew',
  wingletsSharklets: 'winglets_sharklets',
  dangerous: 'dangerous',
  certifications: 'certifications',
  etops: 'etops',
  maxAge: 'max_age',
  maxNoiseLevel: 'max_noise_level',
  minApproachCat: 'min_approach_cat',
  aircraftTypes: 'aircraft_types',
  economy: 'economy',
  business: 'business',
  premiumEconomy: 'premium_economy',
  first: 'first',
};
