import { NormalizedDetailedOffer, NormalizedOfferStatus } from '@/types';

export const mockOffers: NormalizedDetailedOffer[] = [
  {
    id: 1,
    status: { id: 101, status: NormalizedOfferStatus.NEW },
    aircraftDetails: {
      pax: 180,
      age: 5,
      type: 'A320',
      mtow: 77000,
      act: false,
      ife: true,
      noise: 3,
      etops: 180,
      isps: true,
      wifi: true,
      region: 'EU',
      layout: 'Y180',
      thrust: 27000,
      engines: 'CFM56',
      imageUrl: '',
      wingtips: true,
      approachCatId: 1,
      galleryOvens: true,
    },
    providerDetails: {
      name: 'Air Europa',
      iosa: true,
      registration: 'EC-MYH',
      certifications: 'EASA',
    },
  },
  {
    id: 2,
    status: { id: 102, status: NormalizedOfferStatus.SUBMITTED },
    aircraftDetails: {
      pax: 160,
      age: 8,
      type: 'B737-800',
      mtow: 79015,
      act: true,
      ife: false,
      noise: 3,
      etops: 120,
      isps: true,
      wifi: false,
      region: 'ME',
      layout: 'Y160',
      thrust: 26000,
      engines: 'CFM56-7B',
      imageUrl: '',
      wingtips: true,
      approachCatId: 2,
      galleryOvens: false,
    },
    providerDetails: {
      name: 'FlyDubai',
      iosa: true,
      registration: 'A6-FDD',
      certifications: 'EASA',
    },
  },
  {
    id: 3,
    status: { id: 103, status: NormalizedOfferStatus.CONFIRMED },
    aircraftDetails: {
      pax: 220,
      age: 4,
      type: 'A321',
      mtow: 89000,
      act: true,
      ife: true,
      noise: 3,
      etops: 180,
      isps: true,
      wifi: true,
      region: 'EU',
      layout: 'Y220',
      thrust: 32000,
      engines: 'CFM LEAP-1A',
      imageUrl: '',
      wingtips: true,
      approachCatId: 1,
      galleryOvens: true,
    },
    providerDetails: {
      name: 'Lufthansa',
      iosa: true,
      registration: 'D-AIEA',
      certifications: 'EASA',
    },
  },
  {
    id: 4,
    status: { id: 104, status: NormalizedOfferStatus.DECLINE },
    aircraftDetails: {
      pax: 140,
      age: 10,
      type: 'B737-700',
      mtow: 70000,
      act: false,
      ife: false,
      noise: 3,
      etops: 0,
      isps: true,
      wifi: false,
      region: 'AF',
      layout: 'Y140',
      thrust: 24000,
      engines: 'CFM56-7B',
      imageUrl: '',
      wingtips: false,
      approachCatId: 2,
      galleryOvens: false,
    },
    providerDetails: {
      name: 'Kenya Airways',
      iosa: true,
      registration: '5Y-KQX',
      certifications: 'FAA',
    },
  },
  {
    id: 5,
    status: { id: 105, status: NormalizedOfferStatus.NEW },
    aircraftDetails: {
      pax: 100,
      age: 6,
      type: 'E190',
      mtow: 51000,
      act: false,
      ife: false,
      noise: 4,
      etops: 0,
      isps: true,
      wifi: true,
      region: 'US',
      layout: 'Y100',
      thrust: 20000,
      engines: 'GE CF34',
      imageUrl: '',
      wingtips: true,
      approachCatId: 1,
      galleryOvens: false,
    },
    providerDetails: {
      name: 'JetBlue',
      iosa: true,
      registration: 'N304JB',
      certifications: 'FAA',
    },
  },
  {
    id: 6,
    status: { id: 106, status: NormalizedOfferStatus.SUBMITTED },
    aircraftDetails: {
      pax: 250,
      age: 3,
      type: 'B767-300',
      mtow: 186000,
      act: true,
      ife: true,
      noise: 4,
      etops: 180,
      isps: true,
      wifi: true,
      region: 'EU',
      layout: 'Y250',
      thrust: 60000,
      engines: 'PW4060',
      imageUrl: '',
      wingtips: false,
      approachCatId: 3,
      galleryOvens: true,
    },
    providerDetails: {
      name: 'Icelandair',
      iosa: true,
      registration: 'TF-ISW',
      certifications: 'EASA',
    },
  },
  {
    id: 7,
    status: { id: 107, status: NormalizedOfferStatus.CONFIRMED },
    aircraftDetails: {
      pax: 300,
      age: 2,
      type: 'A330-300',
      mtow: 242000,
      act: true,
      ife: true,
      noise: 4,
      etops: 240,
      isps: true,
      wifi: true,
      region: 'ASIA',
      layout: 'Y300',
      thrust: 72000,
      engines: 'RR Trent 700',
      imageUrl: '',
      wingtips: false,
      approachCatId: 3,
      galleryOvens: true,
    },
    providerDetails: {
      name: 'Singapore Airlines',
      iosa: true,
      registration: '9V-SSA',
      certifications: 'EASA',
    },
  },
  {
    id: 8,
    status: { id: 108, status: NormalizedOfferStatus.NEW },
    aircraftDetails: {
      pax: 180,
      age: 7,
      type: 'A320neo',
      mtow: 79000,
      act: true,
      ife: true,
      noise: 3,
      etops: 180,
      isps: true,
      wifi: true,
      region: 'EU',
      layout: 'Y180',
      thrust: 30000,
      engines: 'CFM LEAP-1A',
      imageUrl: '',
      wingtips: true,
      approachCatId: 1,
      galleryOvens: false,
    },
    providerDetails: {
      name: 'Wizz Air',
      iosa: true,
      registration: 'HA-LJA',
      certifications: 'EASA',
    },
  },
  {
    id: 9,
    status: { id: 109, status: NormalizedOfferStatus.SUBMITTED },
    aircraftDetails: {
      pax: 130,
      age: 11,
      type: 'CRJ-900',
      mtow: 38000,
      act: false,
      ife: false,
      noise: 4,
      etops: 0,
      isps: true,
      wifi: false,
      region: 'US',
      layout: 'Y130',
      thrust: 14000,
      engines: 'GE CF34',
      imageUrl: '',
      wingtips: true,
      approachCatId: 1,
      galleryOvens: false,
    },
    providerDetails: {
      name: 'Delta Connection',
      iosa: true,
      registration: 'N589NN',
      certifications: 'FAA',
    },
  },
  {
    id: 10,
    status: { id: 110, status: NormalizedOfferStatus.CONFIRMED },
    aircraftDetails: {
      pax: 310,
      age: 3,
      type: 'B787-9',
      mtow: 254000,
      act: true,
      ife: true,
      noise: 4,
      etops: 330,
      isps: true,
      wifi: true,
      region: 'ASIA',
      layout: 'Y310',
      thrust: 74000,
      engines: 'GEnx-1B',
      imageUrl: '',
      wingtips: true,
      approachCatId: 3,
      galleryOvens: true,
    },
    providerDetails: {
      name: 'ANA',
      iosa: true,
      registration: 'JA894A',
      certifications: 'EASA',
    },
  },
];
