name: Build and deploy Node.js app to Azure Web App - acmi

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install deps & build
        working-directory: acmi
        run: |
          npm ci
          npm run build

      - name: Pack standalone bundle
        working-directory: acmi
        run: |
          rm -rf deploy && mkdir -p deploy/.next
          # runtime (включая нужные node_modules)
          cp -r .next/standalone/* deploy/
          # статика
          cp -r .next/static deploy/.next/static
          # public (если нужен)
          [ -d public ] && cp -r public deploy/public || true

          # # (опционально) package.json/lock, если свой server.js
          # [ -f package.json ] && cp package.json deploy/ || true
          # [ -f package-lock.json ] && cp package-lock.json deploy/ || true

          # архив
          (cd deploy && zip -r ../app.zip .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: acmi/app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: webapp
          path: .

      - name: Sleep a bit (избежать перезапуска SCM)
        run: sleep 15

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: acmi
          slot-name: Production
          package: app.zip
          startup-command: 'node server.js'
          clean: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_282C29550F824997AA71828E4BE07D11 }}
