name: Build and deploy Next.js app to Azure Web App – acmi (Oryx build)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip source for Oryx build
        run: |
          cd acmi
          zip -r ../release.zip . -x "node_modules/*" ".next/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d acmi-dist

      - name: Deploy to Azure Web App with Oryx build
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: acmi
          slot-name: Production
          package: acmi-dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_282C29550F824997AA71828E4BE07D11 }}
          enable-oryx-build: true
